### ISSUE TITLE
Picture shot tests

### ISSUE THREAD

**Issue by magadan** [samtap/fang-hacks#82]
Hello, its possible to take a picture (not video) with this camera ?

Will be interesting to have this option and automated to take picture shots of multiple cameras at same time !

Someone can publish a demo pictures to see the quality of this camera ? Thank you

**Comment by magadan** [comment]
More one info, im searching if is possible to do a 3D Scan rig with this camera, with 40 units.

I really need to know if is possible to create a interface and take pictures of all cameras, and sent to windows ( smb folder ), or ftp upload. 

Example: http://i.imgur.com/oq4vsLu.jpg

**Comment by dmolner** [comment]
Hello,

You can use ispy for take a photo.
This is the quality
webcam.molner.com
The two first  images are resized to 800x600

Best Regards,
David


El dia 1 abr. 2017 1:27 a. m., "Cristian Magadan" <notifications@github.com>
va escriure:

More one info, im searching if is possible to do a 3D Scan rig with this
camera, with 40 units.

I really need to know if is possible to create a interface and take
pictures of all cameras, and sent to windows ( smb folder ), or ftp upload.

Example: http://i.imgur.com/oq4vsLu.jpg

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/samtap/fang-hacks/issues/82#issuecomment-290862144>,
or mute
the thread

**Comment by samtap** [comment]
This is already requested in #39, please put any ideas or other info on that issue
