### ISSUE TITLE
Add crontab support

### ISSUE THREAD

**Issue by ageorgios** [samtap/fang-hacks#98]
since there is no crontab, is there a way to schedule a daily reboot?

**Comment by bbbenji** [comment]
Why would you want to reboot it daily?

**Comment by samtap** [comment]
I'll enable cron in busybox, should be straightforward.

**Comment by ageorgios** [comment]
Thank you!

**Comment by thanme** [comment]
I've just finished messing around with this :)

I basically created a startup script for crond (called 03-crond)

The start bit looks like this:

start()
{
  echo "Starting crond..."
  mkdir -p '/var/spool/cron/crontabs'
  ln -s /media/mmcblk0p2/data/etc/crontab /var/spool/cron/crontabs/root
  crond
  echo "$!" > "$PIDFILE"
}

Then you put what you want in /media/mmcblk0p2/data/etc/crontab

Just note that anything you update with crontab -e won't save on reboot because it recreates  /var/spool/cron/crontabs/root on every edit. There's probably a work around, but this works just fine :) I suppose you could copy the crontabs/root file back on stop or something.

**Comment by wiziwk** [comment]
@samtap  I am new to busybox. Could you elaborate how? Tq.

**Comment by Powerbless** [comment]
> I've just finished messing around with this :)
> 
> I basically created a startup script for crond (called 03-crond)
> 
> The start bit looks like this:
> 
> start()
> {
> echo "Starting crond..."
> mkdir -p '/var/spool/cron/crontabs'
> ln -s /media/mmcblk0p2/data/etc/crontab /var/spool/cron/crontabs/root
> crond
> echo "$!" > "$PIDFILE"
> }
> 
> Then you put what you want in /media/mmcblk0p2/data/etc/crontab
> 
> Just note that anything you update with crontab -e won't save on reboot because it recreates /var/spool/cron/crontabs/root on every edit. There's probably a work around, but this works just fine :) I suppose you could copy the crontabs/root file back on stop or something.

thank. PLEASE NOTE that you must add a "start" at the end of your script(without "") else the command would not start. And after that you have to
chmod -R 777 /media/mmcblk0p2/data/etc/scripts/03-crond
